"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Application = exports.runtimeInjector = exports.Register = exports.Prov = exports.Input = exports.createRegisterLoader = exports.ApplicationPlugin = exports.PLATFORM_SCOPE = void 0;
var platform_1 = require("@hwy-fm/core/platform");
var decorator_1 = require("@hwy-fm/core/platform/decorator");
var token_1 = require("@hwy-fm/core/token");
var index_1 = require("./index");
var platform_2 = require("@hwy-fm/core/platform");
Object.defineProperty(exports, "PLATFORM_SCOPE", { enumerable: true, get: function () { return platform_2.PLATFORM_SCOPE; } });
var runtime_1 = require("@hwy-fm/csr/platform/runtime");
Object.defineProperty(exports, "ApplicationPlugin", { enumerable: true, get: function () { return runtime_1.ApplicationPlugin; } });
Object.defineProperty(exports, "createRegisterLoader", { enumerable: true, get: function () { return runtime_1.createRegisterLoader; } });
Object.defineProperty(exports, "Input", { enumerable: true, get: function () { return runtime_1.Input; } });
Object.defineProperty(exports, "Prov", { enumerable: true, get: function () { return runtime_1.Prov; } });
Object.defineProperty(exports, "Register", { enumerable: true, get: function () { return runtime_1.Register; } });
Object.defineProperty(exports, "runtimeInjector", { enumerable: true, get: function () { return runtime_1.runtimeInjector; } });
exports.Application = (0, decorator_1.makeApplication)(function (applicationContext) {
    var createPlatform = (0, platform_1.createPlatformFactory)(null, [{ provide: token_1.PLATFORM, useClass: index_1.Platform }]);
    createPlatform(applicationContext).bootstrapRender(applicationContext.providers);
});
