"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Prov = exports.PLATFORM_SCOPE = exports.dynamicPlatform = exports.Application = void 0;
var tslib_1 = require("tslib");
// export { AppContextService } from './providers/app-context';
// export { JsonConfigService } from './providers/json-config';
var platform_1 = require("./providers/platform");
Object.defineProperty(exports, "Application", { enumerable: true, get: function () { return platform_1.Application; } });
Object.defineProperty(exports, "dynamicPlatform", { enumerable: true, get: function () { return platform_1.dynamicPlatform; } });
Object.defineProperty(exports, "PLATFORM_SCOPE", { enumerable: true, get: function () { return platform_1.PLATFORM_SCOPE; } });
Object.defineProperty(exports, "Prov", { enumerable: true, get: function () { return platform_1.Prov; } });
tslib_1.__exportStar(require("@fm/core"), exports);
