"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Prov = exports.PLATFORM_SCOPE = exports.Input = exports.dynamicPlatform = exports.Application = void 0;
var tslib_1 = require("tslib");
var runtime_1 = require("./platform/runtime");
Object.defineProperty(exports, "Application", { enumerable: true, get: function () { return runtime_1.Application; } });
Object.defineProperty(exports, "dynamicPlatform", { enumerable: true, get: function () { return runtime_1.dynamicPlatform; } });
Object.defineProperty(exports, "Input", { enumerable: true, get: function () { return runtime_1.Input; } });
Object.defineProperty(exports, "PLATFORM_SCOPE", { enumerable: true, get: function () { return runtime_1.PLATFORM_SCOPE; } });
Object.defineProperty(exports, "Prov", { enumerable: true, get: function () { return runtime_1.Prov; } });
tslib_1.__exportStar(require("@fm/core"), exports);
